### ISSUE TITLE
Site is down :)

### ISSUE THREAD

**Issue by binarykitchen** [ODNZSL/nzsl-online#486]
Hello guys, since everyone is on holiday and have nowhere else I can report and expect to get this fixed asap, I'll try it here (and am a Deaf programmer btw)

So yeah the site is having problems. Can't open start page and there are errors when running searches.

Known issue?

**Comment by Br3nda** [comment]
Hello and welcome Michael.

Ive had a quick test and it's all working for me. Can you give us some more info to work with? 

What errors do you get when you run search? What were you searching for? 

And by "start page" do you mean https://www.nzsl.nz?  You mentioned you can't open it, what happens when you try?

**Comment by binarykitchen** [comment]
It's https://nzsl.vuw.ac.nz/

**Comment by binarykitchen** [comment]
![screen shot 2018-12-29 at 16 02 12](https://user-images.githubusercontent.com/177641/50532777-1f952480-0b83-11e9-97c0-5c74691d77b8.png)

**Comment by binarykitchen** [comment]
And suddenly it works now. Did you fix anything just now?

**Comment by Br3nda** [comment]
I'm not sure why the old vuw one is running again. It used to be a redirect to the new website.

**Comment by eoinkelly** [comment]
I had to look this up but both

* https://nzsl.vuw.ac.nz
* https://www.nzsl.nz

are valid URLs for the app (the Heroku app lists both of them on the settings page). 

Looking at the exception monitoring, it seems like there were a bunch of `Message: Failed to open TCP connection to nzsl-assets.vuw.ac.nz:80 (Connection refused - connect(2) for "nzsl-assets.vuw.ac.nz" port 80)
` errors for approx 4-6 hours in the middle of the day on the 28th and 29th of December.

That error means that the app was unable to reach the assets server during those periods for some reason. The problem seems to be resolved now.

I think we should definitely not 500 when we can't get sign images/videos but I'm not sure what we can do about the connectivity issues except have a chat to Vic folk when everybody is back and see if they can shed any light on it.

**Comment by eoinkelly** [comment]
I'm going to close this now because Issue #489 has the actionable stuff.
