### ISSUE TITLE
Document what browsers we want to support in README

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#585]
We haven't documented which browsers & browser versions we want to support in 2019. Knowing this will let anybody working on CSS or JS know what their constraints are. 

Can we say say that we only care about supporting the last 2 major versions of each of the major browsers (MS Edge, Safari, Firefox, Chrome) or do we still need to support old IE?

Supporting old browsers (especially IE 11 and older) will make front-end dev take longer and limit the features we have available so we should only continue to support IE 11 if we have a good reason to do so. @DSRU The google analytics should give you a breakdown of what browsers are visiting the site to help make the decision.

I am happy to document whatever we come up with here in the README for future devs.

**Comment by Br3nda** [comment]
New relic may have browser info too

**Comment by DSRU** [comment]
Due to the demographics of our dictionary users, we know that there are quite a few of our core audience who will only have access to older technology so we would like to support as many legacy browsers as we can. Having said that, the vast majority of users use Chrome (58%) or Safari (18%). Approximately 10% use IE, and of those, the most used versions are IE9 and IE11. In total there have been about 4,000 users using IE over the past year. I think that's still worth supporting.

For Chrome, there are still a few hundred users using versions as far back as 49.0 but the majority is on 65.0 and above.

Our guideline in the past has been that core functionality (carry out a search, play a video, add signs to a vocab sheet for printing) should be maintained for users who are stuck with a particular browser version because of technology limitations;  otherwise the site shows a message warning that it may not display properly and directs users to sites where they can upgrade their browser.

**Comment by eoinkelly** [comment]
Related to this, the lib we are using to do browser detection is deprecating the way we have been doing it - see https://github.com/fnando/browser/issues/435 

I'm going to look into alternatives.

**Comment by eoinkelly** [comment]
I did some testing as part of PR #983 and FYI we currently support IE 10 but not IE 9 (my changes in PR #983 do not change that).
