### ISSUE TITLE
Images broken on pdf view of vocab sheet 

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#718]
From @DSRU 

> Just tested on staging (which is running very slow on Chrome, a bit better on Firefox). All seems to be working except for broken links to the images when saved to pdf directly. If saving as pdf via the print menu, images download correctly.

**Comment by Br3nda** [comment]
![62330665-73972b80-b50d-11e9-9e19-ed2653f0fcb7](https://user-images.githubusercontent.com/12266/62343053-9553db00-b52c-11e9-83ae-3cc0af5e5c74.png)

**Comment by eoinkelly** [comment]
@DSRU I can't seem to replicate this on staging or production. Can you give me any more details?

BTW staging is slow because it doesn't use the CDN.

**Comment by eoinkelly** [comment]
Nevermind, I have replicated on staging now (sorry I missed it previously). Production seems fine. I will look into this.

**Comment by eoinkelly** [comment]
I think this is a timing issue. To understand it, we need a little context on how we generate PDFs. We generate PDFs in the following way:

1. Rails renders the "print" version of the vocab sheet page as a string
1. Save that string to a file on disk
1. Load the HTML file from disk into an instance of the Google Chrome browser which is installed on the server.
1. The "Server installed Google Chrome" renders the page as it would normally - it requests assets (CSS, JS, images) from the server just like a browser running on one of our user's laptops would.
1. We tell Chrome the page as a PDF file which we also store on disk
1. We return that PDF file to the user who requested it.

The issue here is in step **4.** above. In step 4 (where the server installed Google Chrome renders the page), it starts with the HTML file we give it but it has to ask the server for all the other files it needs (CSS, JS, Images). _Most_ of these things are fast because they are part of the assets bundle which is baked into Rails **but** rendering sign images is **not fast** on staging. Staging does not have a CDN so requests for sign images have to be processed by the Rails app (which in turn downloads them from Freelex). 

I think that what we are seeing is that Chrome is not waiting for the sign images to load properly before creating the PDF.

**Comment by eoinkelly** [comment]
PR #726 hasn't fixed this. More investigation required.

**Comment by Br3nda** [comment]
If there's no db schema change, you can temporarily deploy another git branch to staging, to make debug easier.

**Comment by eoinkelly** [comment]
Fixed by https://github.com/ODNZSL/nzsl-online/commit/1b262ae8c2001a31d995092c3623acb229dfde96
