### ISSUE TITLE
New relic yes or no?

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#864]
New relic gem is added, but there's not new relic resource on heroku (staging or prod)
do we want to use new relic stats?

**Comment by eoinkelly** [comment]
IIRC the gem is sending data to a New Relic which was created outside of Heroku. I can send you creds via email (or we could re-create a new NR account as Heroku addon which would probably be simpler in the long run).

NR was really handy to help figure out where our perf bottlenecks were. We haven't made much progress on that recently because we were waiting for some change to how assets are hosted (that is the main perf bottleneck). Those changes should land soon so we might be able to start dealing with the other perf issues and NR would be handy for that.

I suggest we 
1. Create a new NR account as a Heroku addon so all admins can access easily
1. create a `NEW_RELIC_ENABLED=yes|no` env var and tweak things to only load NR if that' is set - then we can leave NR off by default but I can turn it on easily if I need to gather metrics for a while.

**Comment by eoinkelly** [comment]
I have just created Heroku addons for staging and production and configured the app to use those.

**Comment by eoinkelly** [comment]
PR #980 implements the env var toggling.
